version: '3'

services:
  app:
    build: .
    ports:
      - '5000:5000'
    container_name: app
    volumes:
      - ./migrations:/app/migrations
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=inn_time_db_password
      - POSTGRES_DB=inn_time
    container_name: db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
