"""empty message

Revision ID: 23a4c7beccea
Revises: c9c1c83afc59
Create Date: 2023-07-03 06:40:31.590522

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '23a4c7beccea'
down_revision = 'c9c1c83afc59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        op.execute("CREATE TYPE course_type_enum AS ENUM ('lec', 'tut', 'lab')")
        batch_op.add_column(sa.Column('type', sa.Enum('lec', 'tut', 'lab', name='course_type_enum'), nullable=True))
        batch_op.alter_column('day_of_week',
               existing_type=postgresql.ENUM('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday', name='days_of_week_enum'),
               nullable=False)

    with op.batch_alter_table('electives', schema=None) as batch_op:
        op.execute("CREATE TYPE elective_type_enum AS ENUM ('bs-tech', 'ms-tech', 'hum')")
        batch_op.add_column(sa.Column('type', sa.Enum('lec', 'tut', 'lab', name='elective_type_enum'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('electives', schema=None) as batch_op:
        batch_op.drop_column('type')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('day_of_week',
               existing_type=postgresql.ENUM('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday', name='days_of_week_enum'),
               nullable=True)
        batch_op.drop_column('type')

    # ### end Alembic commands ###
