"""empty message

Revision ID: 9dd74f2127b3
Revises: 23a4c7beccea
Create Date: 2023-07-03 13:42:35.367478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dd74f2127b3'
down_revision = '23a4c7beccea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint('courses_course_name_key', type_='unique')

    with op.batch_alter_table('electives', schema=None) as batch_op:
        batch_op.drop_constraint('electives_elective_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('electives', schema=None) as batch_op:
        batch_op.create_unique_constraint('electives_elective_name_key', ['elective_name'])

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_unique_constraint('courses_course_name_key', ['course_name'])

    # ### end Alembic commands ###
