name: tests
on:
  push:
  workflow_dispatch:

jobs:
  tests:
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: inn_time_db_password
          POSTGRES_DB: inn_time
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Flask db upgrade
      run: |
        flask db upgrade
    - name: Test with pytest
      run: |
        python -m pytest
  
